peter-wangxu/persist-queue

.coveragerc
.testr.conf
README.rst
circle.yml
persistqueue/__init__.py
test-requirements.txt
tox.ini

[GH-1]Use nose2 for testing

---

README.rst
circle.yml
persistqueue/__init__.py
persistqueue/queue.py
setup.py
test-requirements.txt
tests/test_queue.py
tox.ini

* Implements a windows ftruncate function
* Increase code coverage

[GH-2]Add windows support

---

appveyor.yml
circle.yml
setup.py
tox.ini

Also add CI configuration for python3.6.

Add python3.6 support

---

README.rst

Always use latest python version.

Update circle CI

---

LICENSE
README.rst
persistqueue/__init__.py
setup.py

This patch removes original apache v2 license.

Use BSD license

---

persistqueue/__init__.py
persistqueue/exceptions.py
persistqueue/queue.py

Remove Full and Empty exception from Queue, and define them
in persistqueue.

Don't use Queue from standard lib

---

README.rst
persistqueue/__init__.py
persistqueue/queue.py
persistqueue/sqlqueue.py
test-requirements.txt
tests/test_queue.py
tests/test_sqlqueue.py
tox.ini

A SQLiteQueue and a FILOSQLiteQueue are added.

Add SQLite3 base Queue

---

README.rst
circle.yml
persistqueue/pdict.py
persistqueue/queue.py
persistqueue/sqlbase.py
persistqueue/sqlqueue.py

Adjust the doc and update the CI python version

Prefer sqlite3 queue over the file queue

---

persistqueue/queue.py
persistqueue/sqlbase.py
persistqueue/sqlqueue.py
tests/test_queue.py
tests/test_sqlqueue.py

This applies to both sqlite queue and file queue
fixes #36

Fix incorrect behavior of task_done

---

tests/test_sqlqueue.py

Adds UniqueQ test for multiple consumers

[GH-50]Tests the UniqueQ issue

---

persistqueue/queue.py

Uses os.replace for python 3.3+.
For python < 3.3 uses ctypes as @Dobatymo suggested.

Atomic Rename on Windows

---

persistqueue/queue.py
tests/test_queue.py

Fix some CI issue

---

persistqueue/pdict.py
persistqueue/sqlackqueue.py
persistqueue/sqlbase.py
persistqueue/sqlqueue.py
tests/test_sqlackqueue.py
tests/test_sqlqueue.py

* Adds a serializer option to all sqlqueue and pdict data structures
* Removes sqlbase.protocol field

Enable non-pickle serializers

---

persistqueue/sqlackqueue.py

Don't log queue item contents. Resolves #96

---

persistqueue/serializers/__init__.py
persistqueue/tests/test_queue.py
persistqueue/tests/test_sqlqueue.py

Remove the importing of msgpack when install

---

persistqueue/sqlbase.py

Quote table name for safety

---

README.rst
persistqueue/queue.py
persistqueue/sqlbase.py
persistqueue/tests/test_queue.py
persistqueue/tests/test_sqlqueue.py

User now can use "del q" to recalim related resources
fixes #110

Allow explicit reclamation of resources

---

persistqueue/sqlqueue.py
persistqueue/tests/test_sqlqueue.py

Hello @peter-wangxu,
Just a PR related to #155, adding `SQLiteQueue.get_nowait`. I can edit the PR with `put_nowait` if you want but I will need your answer on the issue before because I suspect this is not as simple as I may think.

Adding SQLiteQueue.get_nowait

---

persistqueue/sqlqueue.py

Adding SQLiteQueue.put_nowait

---

README.rst

Fixing docs example related to serializer

---

.gitignore
README.rst
persistqueue/__init__.py
persistqueue/queue.py

Update doc for file based queue

---

persistqueue/__init__.py

Adding missing exports in __init__.py from sqlackqueue

---

persistqueue/sqlbase.py

This adds a public method that cleans up the sqlite3 connections.

add sqlite3 cleanup method

---

README.rst
scripts/publish.sh
setup.cfg
setup.py
tox.ini

Preparation for version 1.0.0-alpha

pre-release of version 1.0.0

---

.gitignore
README.rst
persistqueue/__init__.py
persistqueue/priorityqueue.py
persistqueue/tests/test_priorityqueue.py

Add priority queue for sql based queue
