- MANIFEST.in
This adds LICENSE and the documentation files to
the source tarball generated by setuptools.
The LICENSE text is important for packaging this
library into the Fedora distribution.
> Include LICENSE and doc files in sdist

- README.rst
- persistqueue/__init__.py
- persistqueue/sqlqueue.py
If the specified path is not existed, the sql queue will
fail to create.
This patch fix this issue.
> Fix a minor issue when path does not exist

- README.rst
- persistqueue/sqlbase.py
- persistqueue/sqlqueue.py
- tests/test_sqlqueue.py
The `get` previously is not atomic since it contains 2 sql, a
select and a update. This patch will add a lock for the get operation
for data synchronization.
> [GH-19]Make sure thread-safe for get of sqlqueue

- README.rst
- benchmark/run_benchmark.py
- persistqueue/__init__.py
- persistqueue/pdict.py
- persistqueue/queue.py
- persistqueue/sqlbase.py
- persistqueue/sqlqueue.py
- tests/test_sqlqueue.py
Performance optimization for sqlite3 based queue
Previously, each put/get is done within transaction. Since sqlite3
can only perform few dozen transaction per second, it's practical to avoid
transaction for each put/get.
In this patch, sqlite3 based queues accept the
*auto_commit=[True|False]* when initialization, when auto_commit=False is
set user need to perform *queue.task_done()* after a bulk of putting/getting
to commit all the changes made.
``auto_commit=True`` keeps the previous behavior.
> Performance optimization for sqlite3 based queue

- persistqueue/__init__.py
- persistqueue/sqlbase.py
- tests/test_sqlqueue.py
When using the in-memory database, a directory named
:memory: was created accidentally thus a disk based
queue was setup.
This patch will fix it and stores the data in the memory
directly.
> [GH-22]Fix issue when using :memory: as path

- persistqueue/sqlbase.py
In v0.3.0, auto_commit=False is set as default, this is incompatible
with previous behavior, this change revert to auto_commit=True to
avoid any confusion.
fixes #24
> [GH-24]Revert auto_commit=True for compatability

- persistqueue/sqlbase.py
- persistqueue/sqlqueue.py
- tests/test_sqlqueue.py
Enable "Write-Ahead Logging" by default
* WAL is significantly faster in most scenarios.
* WAL provides more concurrency as readers do not block writers and a writer
does not block readers. Reading and writing can proceed concurrently.
* Disk I/O operations tends to be more sequential using WAL.
* WAL uses many fewer fsync() operations and is thus less vulnerable to
problems on systems where the fsync() system call is broken.
REF: https://sqlite.org/wal.html
fixes #24
> [GH-24]Speed up sqlite queue using WAL

- persistqueue/sqlqueue.py
the event is not cleared when queue is empty which
cause high cpu consumption
> [GH-29]Fix cpu bound when queue is empty

- .circleci/config.yml
- README.rst
- persistqueue/__init__.py
- persistqueue/common.py
- persistqueue/pdict.py
- persistqueue/queue.py
- persistqueue/sqlbase.py
- persistqueue/sqlqueue.py
- setup.py
- tests/test_queue.py
- tests/test_sqlqueue.py
By default pickle uses protocol version 0, which is ASCII and not so
efficient (at least in terms of space).
This commit will choose highest protocol available in PythonX.
> [GH-45]Use the highest protocol version for pickle

- persistqueue/sqlackqueue.py
- tests/test_sqlackqueue.py
A simple and light queue support "ack" based on sqlite queue.
The core functions:
get: get from queue and mark item as unack
ack: mark item as acked
nack: there might be something wrong with current cusumer, so mark item as ready and new consumer will get it
ack_failed: there might be something wrong during process, so just mark item as failed.
> add ack support

- persistqueue/sqlbase.py
Currently, if start a new queue object on an existing path
the text_factory of sqlite3 is not set which caused following issue:
"OperationalError: Could not decode to UTF-8 column 'data' with text"
This commit set the text_factory to str if starting on an existing
path
> [GH-58]set text_factory to str after restart

- persistqueue/queue.py
When running file queue on some system configurations(eg, ext4 with
data=journal), the queue data written were not synced to
disk immediately, so a system reset/crash can corrupt the queue file.
This commit force a fsync before closing the queue file, such
ensure data written is flushed to disk.
> [GH-56]Fix queue file corruption after reset

- persistqueue/queue.py
- persistqueue/serializers/json.py
- persistqueue/serializers/msgpack.py
- persistqueue/serializers/pickle.py
- test-requirements.txt
- tests/test_queue.py
I'm interested in using this library, but I'm hesitant to use pickling.
Is it allowable for me to submit some PRs that make it possible to configure another serializer, such as json or msgpack?
Also, this PR should fix a couple bugs:
* if `path` exists, such as when resuming a queue after restart, then `self.protocol` would be `None`
* `_put()` wasn't actually using `self.protocol`, so it would fall back to version 0
> Allow configuring serializer in file based queue

- extra-requirements.txt
- persistqueue/queue.py
- setup.py
If the tmp dir was not on the same partition of
the queue path, we need to set the temp dir to
queue path so that os.rename can work as expected
> [GH-64]Automatic select temp dir

- persistqueue/__init__.py
I have machines with Freebsd 11.1 and Python 2.7.14. Unfortunately, I can't install the dev bindings (not packaged).
I would like to use the file-based queue functionality.
```
Traceback (most recent call last):
File "/usr/local/apps/myapp/cron.py", line 9, in <module>
from persistqueue import Queue
File "/usr/local/lib/python2.7/site-packages/persistqueue/__init__.py", line 7, in <module>
from .pdict import PDict  # noqa
File "/usr/local/lib/python2.7/site-packages/persistqueue/pdict.py", line 4, in <module>
import sqlite3
File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
from dbapi2 import *
File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
from _sqlite3 import *
ImportError: No module named _sqlite3
```
Issue: ImportError: No module named …
> Fix: ImportError: No module named _sqlite3

- persistqueue/__init__.py
- persistqueue/sqlackqueue.py
- persistqueue/sqlqueue.py
- tests/test_sqlackqueue.py
- tests/test_sqlqueue.py
the 0 was treated as an invalid user input incorrectly,
so that 0 was ignored when `get` and user may be blocked if 0 is
the last value in the queue
> [GH-79]Fix issue when storing 0 as value

- .circleci/config.yml
- persistqueue/serializers/__init__.py
- persistqueue/serializers/json.py
- persistqueue/serializers/msgpack.py
- persistqueue/serializers/pickle.py
- persistqueue/sqlackqueue.py
- persistqueue/sqlqueue.py
- persistqueue/tests/test_sqlqueue.py
The problem this pull request is trying to solve is the following:
```python
>>> d1 = {"foo": 1, "bar": 2}
>>> d2 = {"bar": 2, "foo": 1}
>>> json.dumps(d1)
'{"foo": 1, "bar": 2}'
>>> json.dumps(d2)
'{"bar": 2, "foo": 1}'
```
Order of keys depends on the dictionary initialization order. But if we force `sort_keys` then the encoded values will be identical which will solve the problem with `UniequeQueue`
```python
>>> json.dumps(d1, sort_keys=True) == json.dumps(d2, sort_keys=True)
True
```
There is no simple way to solve this problem with the `msgpack` or `pickle` serializer, except doing something like this:
```python
if isinstance(obj, dict):
obj = {
key: obj[key]
in sorted(obj)
}
pickle/msgpack.dumps(obj)
```
```python
>>> (
msgpack.dumps({key: d1[key] for key in sorted(d1)}) == …
```
> Fix UniqueQueue dictionary problem with json serializer.

- persistqueue/sqlbase.py
> [GH-99]Support db_file_name when creating queue

- persistqueue/queue.py
- persistqueue/sqlackqueue.py
- persistqueue/sqlqueue.py
- persistqueue/tests/test_queue.py
- persistqueue/tests/test_sqlackqueue.py
- persistqueue/tests/test_sqlqueue.py
Hello @peter-wangxu,
Here is the aforementioned PR. Fixes #114 
I hope the tests are placed correctly.
Have a good day
> Adding #.empty to relevant queues

- persistqueue/queue.py
- persistqueue/tests/test_queue.py
`Queue.__del__` attempts to use `closed` and `close()` on `self.info`, but `self.info` is a dict and there's nothing to close. Just removing it from the removal list.
example (python 3.6):
```
>>> from persistqueue import Queue
>>> q = Queue('/tmp')
>>> del q
Exception ignored in: <bound method Queue.__del__ of <persistqueue.queue.Queue object at 0x7f01a45d0cc0>>
Traceback (most recent call last):
File "/home/ahusak/scratch/persist-queue/persistqueue/queue.py", line 300, in __del__
if to_close and not to_close.closed:
AttributeError: 'dict' object has no attribute 'closed'
```
I think because this happens in `__del__`, you can see the exception is ignored rather than raised. So the unit tests definitely complain about this but succeed regardless. Not sure how to write a unit_test around …
> fix AttributeError in Queue.__del__

- README.rst
- benchmark/run_benchmark.py
- persistqueue/queue.py
- persistqueue/tests/test_queue.py
Adds an optional `autosave` parameter to the file Queue, which will automatically save on `get()` rather than a separate call to `task_done()`. Existing behavior remains the same, it should be backwards compatible.
I went with the name `autosave` as `auto_commit` has specific meaning to SQL and thought it might be confusing. I can rename it if you'd prefer something different.
I also kept `task_done()` behavior the same _except_ for the actual file saving to allow the most flexibility in usage. The "counting" that `task_done()` does will still work with `join()` regardless of enabling `autosave`.
I added some language in the class docstring as well as the readme. Not sure if I'm being too wordy so I can try and chop it down if necessary. I'm open to suggestions.
I also updated the …
> add optional autosave feature to file Queue

- README.rst
I think my last PR may have screwed up white space and broke the heading in the readme
> whitespace typo on readme heading

- README.rst
- persistqueue/sqlackqueue.py
- persistqueue/tests/test_sqlackqueue.py
> Add VACUUM for SQLiteAckQueue

- persistqueue/exceptions.py
Hello again @peter-wangxu, this is a proposition of making `persistqueue.exceptions` inherit from their standard python `queue` counterparts. I propose this because right now, you cannot make code like this work (when using a `persistqueue` queue of course):
```python
from queue import Empty
try:
queue.get_nowait()
except Empty:
print('empty!')
```
Which means that if you want to use `persistqueue` with code that has been written with python queues in mind, this won't seemlessly work.
> Empty and Full inheriting from python.queue exceptions

- persistqueue/pdict.py
- persistqueue/tests/test_pdict.py
Just a PR adding the `#.get` method to the `PDict`. This method exists on python's `dict` and has been replicated with its default argument. The only compromise I made was to make `default` a kwarg while python's own implementation does not recognize second argument as kwarg (I can edit the PR to march closely what python does by using `*args` which makes the implementation a bit more complex).
This method is often very useful if you want to test existence of an item in the dict as well as getting the attached value in a single operation. This is even truer with the `PDict` since making those two operations would require two SQL queries whereas here only one is sufficient.
> Adding PDict.get

- persistqueue/sqlackqueue.py
`SQLiteAckQueue._MAX_ACKED_LENGTH` used to control `OFFSET`, and was updated to set `max_delete`, which controls `LIMIT`. It should instead set `keep_latest`, which now controls `OFFSET`.
> Fix backward compatibility for _MAX_ACKED_LENGTH

- persistqueue/sqlackqueue.py
- persistqueue/sqlqueue.py
This PR is a quick fix for an obviously misspelled key in the queue data structure (`tiemstamp` should probably be `timestamp`)
> fix misspelled keyword 'tiemstamp' -> 'timestamp'

- persistqueue/sqlackqueue.py
- persistqueue/tests/test_sqlackqueue.py
Changes:
- Fixes #169 
- Added unittests coverage for FILOSQLiteAckQueue and SQLite3UniqueAckQueueTest
> Fix FILOSQLiteAckQueue.get(raw=True) throwing index error.

- persistqueue/sqlackqueue.py
- persistqueue/sqlbase.py
- persistqueue/tests/test_sqlackqueue.py
Seems the prior code didn't work properly and ends up creating a variable of kargs that is equal to **kargs instead of actually just passing the values of kargs.  Same with args.  Did a test and just passing `*args, **kargs` directly will pass the variables properly.
> Fix end of queue increment

- persistqueue/queue.py
If tempdir is not set in Queue initialization, a temporary file is created to test if default tempdir is in the same filesystem as queue path.
This patch deletes this temporary file to avoid accumulation of junk temporary files after several executions.
> Delete temporary file

- README.rst
- persistqueue/__init__.py
- persistqueue/sqlackqueue.py
- persistqueue/sqlbase.py
- persistqueue/tests/test_sqlackqueue.py
- persistqueue/tests/test_sqlqueue.py
Performs a ``VACUUM`` against the sqlite, and rebuild the database file, this usually takes long time and frees a lot of disk space after `get()`
fixes #176
> Add `shrink_disk_usage` for sqlite3 base queues

- README.rst
- extra-requirements.txt
- persist-queue.code-workspace
- persistqueue/serializers/cbor2.py
- persistqueue/tests/test_queue.py
- persistqueue/tests/test_sqlqueue.py
- test-requirements.txt
Add CBOR serializer support, using the `cbor2` package.
CBOR protocol is similar to `msgpack`, however CBOR has a cleaner design, is standardized and preferred over `msgpack` by some.
I modelled the implementation based on the `msgpack` implementation.
I arbitrarily chose `cbor2` 5.2.0 has the minimum version requirement, as this was the first release to make it into a Debian distribution as a pre-built package (Debian 11 Bullseye).  It is likely that earlier `cbor2` versions would also work.
> CBOR serializer (using cbor2 package)

- persistqueue/queue.py
- persistqueue/sqlackqueue.py
- persistqueue/sqlbase.py
- persistqueue/tests/test_mysqlqueue.py
- persistqueue/tests/test_queue.py
- persistqueue/tests/test_sqlackqueue.py
- persistqueue/tests/test_sqlqueue.py
Adds a `full()` API to complement the `empty()` API.
The `full()` API is available in Python3 `queue.Queue` class and this PR makes `persist-queue` more consistent with the `queue.Queue` API.
There doesn't seem to be a notion of a full queue when using database queues.  The `full()` API is provided for consistency and always returns `False`.
> Add full() API and tests

- appveyor.yml
- persistqueue/__init__.py
> fix inproper log of importing

- persistqueue/sqlbase.py
Hello! So if I have some code like this:
```
try:
queue = persistqueue.FIFOSQLiteQueue(path=queue_path, multithreading=True, auto_commit=False)
except sqlite3.OperationalError as e:
logger.error("unable to create the sqlite file for the queue: %s", e)
raise SystemExit(1)
```
But if there is an error creating the queue then I get this error:
```
[2024-06-16 00:06:13,567] ERROR    - unable to create the sqlite file for the queue: unable to open database file
Exception ignored in: <function SQLiteBase.__del__ at 0x104a0dc60>
Traceback (most recent call last):
File "/path/to/lib/python3.12/site-packages/persistqueue/sqlbase.py", line 453, in __del__
self._getter.close()
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```
If there is an error when creating the …
> Check to see if these are empty before closing them.
